#############################################################################
# Makefile for building: painttyWidget
# Generated by qmake (3.0) (Qt 5.0.1) on: ?? ?? 19 23:40:40 2013
# Project:  painttyWidget.pro
# Template: app
# Command: D:\Program\CPP\qt5\qt-5.0.1\x64-static\bin\qmake.exe -spec win32-g++ -o Makefile painttyWidget.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\Program\CPP\qt5\qt-5.0.1\x64-static\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: painttyWidget.pro ../qt5/qt-5.0.1/x64-static/mkspecs/win32-g++/qmake.conf ../qt5/qt-5.0.1/x64-static/mkspecs/features/spec_pre.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/device_config.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/common/shell-win32.conf \
		../qt5/qt-5.0.1/x64-static/mkspecs/qconfig.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_axbase.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_axcontainer.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_axserver.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_bootstrap.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_clucene.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_concurrent.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_core.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_designer.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_designercomponents.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_gui.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_help.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_multimedia.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_network.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_opengl.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_platformsupport.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_printsupport.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_qml.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_qmldevtools.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_qmltest.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_quick.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_quickparticles.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_script.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_scripttools.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_sql.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_svg.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_testlib.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_uitools.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_v8.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_widgets.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_xml.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_dsengine.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qico.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qminimal.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qmng.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qsvg.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qtga.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qtiff.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_qwindows.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/qt_functions.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/qt_config.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/win32-g++/qmake.conf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/spec_post.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/exclusive_builds.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/default_pre.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/win32/default_pre.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/release.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/debug_and_release.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/default_post.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/static.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/c++11.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/win32/rtti.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/warn_on.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/qt.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/resources.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/moc.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/win32/opengl.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/uic.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/win32/windows.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/testcase_targets.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/exceptions.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/yacc.prf \
		../qt5/qt-5.0.1/x64-static/mkspecs/features/lex.prf \
		painttyWidget.pro \
		D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Widgets.prl \
		D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Gui.prl \
		D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Core.prl \
		D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Network.prl \
		D:/Program/CPP/qt5/qt-5.0.1/x64-static/plugins/platforms/qwindows.prl \
		D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5PlatformSupport.prl
	$(QMAKE) -spec win32-g++ -o Makefile painttyWidget.pro
..\qt5\qt-5.0.1\x64-static\mkspecs\features\spec_pre.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\device_config.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\common\shell-win32.conf:
..\qt5\qt-5.0.1\x64-static\mkspecs\qconfig.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_axbase.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_axcontainer.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_axserver.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_bootstrap.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_clucene.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_concurrent.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_core.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_designer.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_designercomponents.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_gui.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_help.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_multimedia.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_network.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_opengl.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_platformsupport.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_printsupport.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_qml.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_qmldevtools.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_qmltest.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_quick.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_quickparticles.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_script.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_scripttools.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_sql.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_svg.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_testlib.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_uitools.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_v8.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_widgets.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_xml.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_dsengine.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qico.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qminimal.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qmng.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qsvg.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qsvgicon.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qtaccessiblequick.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qtga.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qtiff.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qwbmp.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_qwindows.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\qt_functions.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\qt_config.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\win32-g++\qmake.conf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\spec_post.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\exclusive_builds.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\default_pre.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\win32\default_pre.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\release.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\debug_and_release.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\default_post.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\static.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\c++11.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\win32\rtti.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\warn_on.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\qt.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\resources.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\moc.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\win32\opengl.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\uic.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\win32\windows.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\testcase_targets.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\exceptions.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\yacc.prf:
..\qt5\qt-5.0.1\x64-static\mkspecs\features\lex.prf:
painttyWidget.pro:
D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Widgets.prl:
D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Gui.prl:
D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Core.prl:
D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5Network.prl:
D:/Program/CPP/qt5/qt-5.0.1/x64-static/plugins/platforms/qwindows.prl:
D:/Program/CPP/qt5/qt-5.0.1/x64-static/lib/Qt5PlatformSupport.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile painttyWidget.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) D:\Program\CPP\painttyWidget\painttywidget_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
